### ISSUE TITLE
Nondeterministic models for verifiers

### ISSUE THREAD

**Issue by MarcelBulpr** [dlshriver/DNNV#111]
When working with dnnv and verinet, I noticed that the performance between runs can vary a lot. Investigating, I found that the models that dnnv generates and then gives to verinet are not deterministic. They are different between runs.
This seems only to affect specific layers, and I attached a txt file comparing two of the models (| indicate differences, see line 473 and 479).

Is this intended behaviour? And if so, why?

Appreciate any infos.
[difference.txt](https://github.com/dlshriver/dnnv/files/11968182/difference.txt)

**Comment by dlshriver** [comment]
This is generally expected for most complex properties. What are the specifications you are trying to verify?

The reason for this is that we essentially convert the negation of the property to DNF, and then we use the verifier to check each of the disjuncts. The order that we check these is currently random and is not guaranteed to be the same between runs. This means that `unsat` results should generally not vary much in time since all sub-properties must be checked, but `sat` results may return more quickly depending on the ordering.

The behavior is intended. We don't know which sub-properties are more likely to be violated so a random ordering gives us just as good a chance as any. If we had a good heuristic for determining likely `sat`/`unsat` sub-properties we could use that to order them. This could be an interesting avenue of work.

**Comment by MarcelBulpr** [comment]
Thank you for the reply. That makes sense.
