### ISSUE TITLE
property format

### ISSUE THREAD

**Issue by MaxSally** [dlshriver/DNNV#30]
Dear David,

My neural network

```
Verifying Network:
Input_0                         : Input([-1  2], dtype=float64)
MatMul_0                        : MatMul(Input_0, [[ 1. -1.] [ 1.  1.]])
Add_0                           : Add(MatMul_0, [0. 0.])
Relu_0                          : Relu(Add_0)
MatMul_1                        : MatMul(Relu_0, [[ 0.5 -0.2] [-0.5  0.1]])
Add_1                           : Add(MatMul_1, [0. 0.])
Relu_1                          : Relu(Add_1)
MatMul_2                        : MatMul(Relu_1, [[ 1. -1.] [-1.  1.]])
Add_2                           : Add(MatMul_2, [0. 0.])
```

property that I want to verify: ((x0 > x1) && x0 - x1 <= 0) => y0 > y1.

My property file
```
from dnnv.properties import *
import numpy as np
N = Network("N")
x = Image(Parameter("input", type=str))
output_class = np.argmax(N(x))


Forall(x, Implies(And((x_0 > x_1), (x_0 <= -x_1)), N(0) > N(1)))
```
Please let me know if I am correct in translating my desirable property? When I check the logs, it said
```
Verifying property:
Forall(x0, (((x_0 > x_1) & (x_0 <= -x_1)) ==> (N(0) > N(1))))
```
I am not sure about the `Forall(**x0**, ...)

When I run it with ERAN, I also run into this issue, 
```
E tensorflow/stream_executor/cuda/cuda_driver.cc:313
] failed call to cuInit: UNKNOWN ERROR (303)
....
File "DNNV/dnnv/nn/converters/tensorflow/__init__.py", line 350, in input_func
    for d1, d2 in zip(operation.shape[1:], x.shape[1:])

AttributeError: 'int' object has no attribute 'shape'
```

Thank you for taking your time to help me. Have an awesome day.

Best regards,
Max Nguyen

**Comment by dlshriver** [comment]
Thank you for your interest in DNNV! I think the error is due to there being several undefined variables. I'll try to see if we can catch this earlier and give a better error message in the future. There are a few problems that I see with that property specification.

First, `x_0` and `x_1` don't seem to exist. I assume they are supposed to be indexed values of the input tensor, which should be written as `x[0, 0]` and `x[0, 1]` since the input has shape (1, 2).

Second, the network must be run on an input to get an output. 0 and 1 are not valid inputs for the specified network with input shape (1, 2). You can perform network inference just like calling a function `N(x)` where `x` is a network input. It can be either symbolic or concrete. Here it is symbolic because I think you want to say that the expression is true for all inputs `x`. Because the output shape of the network is also (1, 2), you can index the output tensor in the same way you do for the input tensors. `N(x)[0, 0]` will give you the first value (what I believe you called `y_0` and `N(x)[0, 1]` will give you the second.

Third, the `x = Image(Parameter("input", type=str))` is unnecessary here I believe. This line will define `x` to be an image that can be specified at runtime by the `--prop.input` command line argument. I don't think that is what you want here. Because your property doesn't need any concrete input values, you should be safe deleting this line completely.

Finally, `Forall` declares its first argument to be a symbolic variable for which the second expression must be true for all values of that variable. Usually that variable will be a network input, and the specification essentially says that the expression must be true for all network inputs.

I think the following specification captures the behavior that you were trying to specify:

```
from dnnv.properties import *
import numpy as np

N = Network("N")

Forall(x, Implies(And((x[0, 0] > x[0, 1]), (x[0, 0] <= -x[0, 1])), N(x)[0, 0] > N(x)[0, 1]))
```

Let me know if this works for you, and if you have any other questions!

**Comment by MaxSally** [comment]
Dear David,

Thank you for your time and detailed clarification. It helps me a lot in understanding format file. 

Unfortunately, I still encounter this error when using your previous answers. Here is the log.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "dnnv/__init__.py", line 5, in <module>
    from .nn import Operation, OperationVisitor, OperationTransformer
  File "dnnv/nn/__init__.py", line 14
    def try_parse_format(netname: Path) -> str:
                                ^
SyntaxError: invalid syntax
```

Thank you very much. Have a great day.

Best regards,
Max Nguyen

**Comment by dlshriver** [comment]
DNNV requires python3 (python3.7 is highly recommended), but it looks like you are using python2.7. I would suggest using the provided installation scripts (as described in the README) to create a python virtual environment and install the verifiers. If you have used those scripts, then be sure to activate the virtual environment with `source .env.d/openenv.sh` before attempting to run DNNV.

**Comment by MaxSally** [comment]
You are right. I did not activate the virtual environment. After running it. I still ran into this error. 

```
2021-01-25 08:30:29.123268: E tensorflow/stream_executor/cuda/cuda_driver.cc:313
] failed call to cuInit: UNKNOWN ERROR (303)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 63, in <module>
    _main()
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 59, in _main
    main(*cli.parse_args())
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 42, in main
    result = verifier.verify(dnn, phi, **kwargs)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/eran/__init__.py", line 71, in verify
    for prop in property_extractor.extract_from(~phi):
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 393, in e
xtract_from
    yield from self._extract(conjunction)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 371, in _
extract
    self.visit(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 397, in v
isit
    super().visit(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 336, in v
isit
    return visitor(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 421, in v
isit_And
    self.visit(expr)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 397, in v
isit
    super().visit(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 336, in v
isit
    return visitor(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 565, in v
isit_LessThanOrEqual
    self._add_constraint(expression)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 558, in _
add_constraint
    variables, indices, c[1], c[2], is_open=is_open
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/extractors.py", line 209, in u
pdate_constraint
    "HyperRectangle constraints can only constrain a single dimension"
ValueError: HyperRectangle constraints can only constrain a single dimension

```

Is it due to x[0, 1]?

**Comment by dlshriver** [comment]
No, sorry I should have noticed this before. The issue is that the constraint is comparing two dimensions to each other (x_0 and x_1 in your original definition and x[0,0] and x[0,1] in the DNNV spec). This version of DNNV only supports properties whose input constraints can be represented as hyperrectangles, i.e., an interval constraint in each dimension. There is no problem with the output constraints, it is just the input constraints used here that the main branch does not currently support. The upcoming release (currently on the `develop` branch) does support more complex properties for most verifiers and should be able to handle this property. We plan to release an initial version of this in the coming weeks, but you are welcome to try it now by pulling from the develop branch (you will need to re-run all of the installation scripts as many have changed to use newer tool versions).

**Comment by MaxSally** [comment]
I will try the `develop` branch then. Thank you for helping me.

**Comment by MaxSally** [comment]
I have tried it with develop branch. I just do the `git pull` and `./manage.sh init`. When I ran, I got 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 75, in <module>
    exit(_main())
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 71, in _main
    return main(*cli.parse_args())
  File "/home/qhnguyen/DNNV/dnnv/__main__.py", line 22, in main
    phi = properties.parse(args.property, format=args.prop_format, args=extra_ar
gs)
  File "/home/qhnguyen/DNNV/dnnv/properties/parse.py", line 14, in parse
    return parse_dsl(path, args)
  File "/home/qhnguyen/DNNV/dnnv/properties/dsl.py", line 376, in parse
    module = ast.parse(f.read())
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 39: invalid
 continuation byte
```
Is there a change in the encoding when reading property files in develop branch?

**Comment by dlshriver** [comment]
There are some big changes in this version, and unfortunately the command line interface has changed in anticipation for multi-network property support, and to enable additional verifier configuration options to appear in the help message. Some examples of the usage can be seen in the README on the develop branch, or in the [documentation](https://dnnv.readthedocs.io/en/develop/). The basic usage looks like: `python -m dnnv PROPERTY_PATH --network NAME NETWORK_PATH --VERIFIER`, where `PROPERTY_PATH` is the path to the property specification file, `NETWORK_NAME` is the name of a network in the property specification (`N` in your case, and what I generally like to use), `NETWORK_PATH` is the path to your network in the ONNX format, and `VERIFIER` is the verifier that you want to use.

**Comment by MaxSally** [comment]
Thanks a lot. I should have checked the ReadMe. This is my first year doing research, so I am learning on the go.

After running it, I got the same error like before. 
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/DNNV/dnnv/__main__.py", line 75, in <module>
    exit(_main())
  File "/DNNV/dnnv/__main__.py", line 71, in _main
    return main(*cli.parse_args())
  File "/DNNV/dnnv/__main__.py", line 55, in main
    result, cex = verifier.verify(phi, **params)
  File "/DNNV/dnnv/verifiers/common/base.py", line 80, in verify
    return cls(phi, **kwargs).run()
  File "/DNNV/dnnv/verifiers/common/base.py", line 109, in run
    for subproperty in self.reduce_property():
  File "/DNNV/dnnv/verifiers/common/base.py", line 93, in reduce_p
roperty
    ).reduce_property(~self.property):
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 505, in reduce_property
    yield from self._reduce(conjunction)
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 481, in _reduce
    self.visit(expression)
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 516, in visit
    result = visitor(expression)
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 541, in visit_And
    self.visit(expr)
  File "/home/qhnguyen/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 516, in visit
    result = visitor(expression)
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 685, in visit_LessThanOrEqual
    self._add_constraint(expression)
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 678, in _add_constraint
    variables, indices, c[1], c[2], is_open=is_open
  File "/DNNV/dnnv/verifiers/common/reductions/iopolytope.py", lin
e 259, in update_constraint
    "HyperRectangle constraints can only constrain a single dimension"
ValueError: HyperRectangle constraints can only constrain a single dimension
```

Is reinstalling ERAN or other verifiers necessary? I think that it is not necessary. If it is, I notice that in your script if a repository fails to clone, it will stop the execution. It may be inconvenient when switching branches. 

I have double-checked that I am on develop branch.

**Comment by dlshriver** [comment]
Definitely, thanks for asking questions. It helps us both; I like to know how other people are using or want to use DNNV.

Unfortunately everything should be installed from scratch since there are new versions of several dependencies. Are you trying to use ERAN here? Unfortunately ERAN is one of the few verifiers that will not handle this type of input constraint in DNNV yet, we are still working on this support for ERAN. If possible, I would recommend trying Neurify, VeriNet or nnenum. I'm sorry for the inconvenience, we do hope to be able to support this case soon.

**Comment by MaxSally** [comment]
Could you clarify on which input constraints ERAN does not support? I would love to learn about it since I want to get to know more tools.

**Comment by dlshriver** [comment]
ERAN in DNNV currently only supports specifications in which the input constraints can be represented as hyperrectangles, i.e., they can be represented by an interval in each input dimension (e.g., 0 < x < 1). The ERAN verifier in general can support more complex input constraints (they can support what are known as [zonotopes](https://en.wikipedia.org/wiki/Zonohedron)), which we are working to add support for to DNNV, but the conversion from our internal constraint representation to the ERAN zonotope representation is not straightforward.
