### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by MaxSally** [dlshriver/dnnv#34]
Hi David, 

I encounter some problems while running DNNV with Neurify. 

My model:
![example_model](https://user-images.githubusercontent.com/48167397/106193565-4d3e6480-6173-11eb-8bcb-88a203512d3c.PNG)

Initial property (property 1)
```
from dnnv.properties import *
import numpy as np
N = Network("N")

Forall(x, Implies(And((x[0, 0] - x[0, 1] > 0), (x[0, 0] +x[0, 1] <= 0)), N(x)[0, 0] > N(x)[0, 1]))
```
Property 2
```
from dnnv.properties import *
import numpy as np
N = Network("N")

Forall(x, Implies(And((x[0, 0] - x[0, 1] > 0), (x[0, 0] +x[0, 1] <= 0)), N(x)[0, 0] <= N(x)[0, 1]))
```

As you can see, the only difference is in the second half of the implication(N(x)[0, 0] > N(x)[0, 1] vs  (x)[0, 0] <= N(x)[0, 1]); they are opposite to each other. However, with both properties files, I still receive `unsat` for both of them. If I am not mistaken, `unsat` means that the property is proven. The only property that is true is the first one (property 1). Could you take a look at it?

Thank you very much. Have a great day.

Best regards,
Max Nguyen

**Comment by dlshriver** [comment]
I believe the result is correct. In both cases, the antecedent of the implication is false, which means the property evaluates to true for both properties. For property 1 the antecedent is (x0 > x1 and x0 <= x1) which cannot be true for any values of x0 and x1; x0 cannot be both less than x1 and greater than or equal to x1. Similarly, for property 2, the antecedent is (x0 <= x1 and x0 > x1), which also cannot be satisfied for the same reason.

**Comment by MaxSally** [comment]
@dlshriver, I think there is a misunderstandings. My antecedent is (x0 > x1 and x0 <= -x1), not (x0 > x1 and x0 <= x1). One example is (x0 = 5, x1 = -6). Then 5 > -6 and 5 <= -(-6) = 6.

**Comment by dlshriver** [comment]
I'm sorry, you are correct. I must have misread the antecedents. I still believe the results may be correct, since it looks like the two antecedents are different. The first is (x0 > x1 and x0 <= -x1), but the second is (x0 <= x1 and x0 > -x1), so it is possible for both properties to hold since they cover different regions of the input space.

**Comment by MaxSally** [comment]
I am sorry. I had a typo on my second property, so that was why the antecedent was different. I have corrected them. Could you take a look again?

**Comment by dlshriver** [comment]
I think I've figured this one out. The verifiers don't seem to like unbounded input domains. x0 does not have an upper or lower bound, and x1 only has an upper bound. This also causes issues with verifiers other than neurify (I encountered similar issues with planet and nnenum). I'm not sure of an ideal solution for this problem, as it seems to be a requirement of the underlying verifiers, but I will try to detect this in DNNV and output a warning or exception. One way to deal with this right now is to add lower and upper bounds to the input variables in your precondition. For example, you can add `(-1e6 < x < 1e6)` to the And expression and it should fix the issue for now. The bounds can be arbitrarily large, but must be finite.

**Comment by khedher1984** [comment]
Hello, 
I am interested in your tool to check neural networks. last year I used ERAN and now I find that your tool combines several methods and it is interesting. unfortunately, now the installation is a bit complicated because we will have to install the tools independently. I have a problem of use. often I will get an error message as the following picture shows. only reluplex which works without error. could you help me ?
![image](https://user-images.githubusercontent.com/34816981/124594356-fd6d7300-de5f-11eb-9c8d-36ed5c39f193.png)

Thank you Best regards.

**Comment by dlshriver** [comment]
Hi @khedher1984,

Thank you for your interest in DNNV. Is the issue that your having related to this current issue or is it separate?

For your problem, I will need some more information before I can make any suggestions. How are you running DNNV? What network and property are you trying to check? Also, what platform are you running on and what is the full output of trying to run DNNV?

**Comment by dlshriver** [comment]
> I will try to detect this in DNNV and output a warning or exception.

Finally closing this issue. With commit 179941edbaa18e2fa14c58f310f47feec8bd3b02 we now detect unbounded inputs and report an error.
