### ISSUE TITLE
ERAN complete verification?

### ISSUE THREAD

**Issue by j29scott** [dlshriver/DNNV#51]
Is it possible to enable complete verification for ERAN? Unknown results are frequent.

**Comment by dlshriver** [comment]
There is currently not a way to enable complete verification for ERAN in DNNV. We currently only support its abstract interpretation (AI) mode with the 4 domains DeepZono, DeepPoly, RefineZono, and RefinePoly. Unknowns are pretty common with AI due to the large overapproximations that arise for many problems.

**Comment by j29scott** [comment]
Why? is it not sufficient to run with the complete flag and proper domain?

**Comment by dlshriver** [comment]
The complete solver is completely separate from the abstract interpretation solver. Complete mode uses an MILP-based solver which we currently haven't implemented support for. We are not running ERAN using their command line API, since it is limited to only a few datasets and has certain expectations for data normalization on those datasets. We hook into their python API to run verification. We have only done this for the 4 AI methods due to their similarity. We haven't done this for the MILP method mainly because it uses a different underlying API. I also believe it wasn't actually available when we first built DNNV, and we haven't gone back to add support for it.
