### ISSUE TITLE
Docker usage error

### ISSUE THREAD

**Issue by GuantingPan** [dlshriver/DNNV#52]
Hi, 

When I try to use example in docker, it reports error. Is this caused by GPU issue? I don't have GPU installed in my Laptop.
```
(.venv) dnnv@ce1f5b6d0d16:~/tests/artifacts$ export INPUT_LAYER=3
(.venv) dnnv@ce1f5b6d0d16:~/tests/artifacts$ dnnv properties/class_localrobustness_1.py --network N ./networks/mnist_relu_3_50.onnx --neurify
Verifying property:
Forall(x_0, (((((randn(1, N[3:].input_shape[0][1]).astype(<class 'numpy.float32'>)) - 3.0) <= x_0) & (x_0 <= (3.0 + randn(1, N[3:].input_shape[0][1]).astype(<class 'numpy.float32'>)))) ==> (numpy.argmax(N[3:](x_0)) == numpy.argmax(N[3:]((randn(1, N[3:].input_shape[0][1]).astype(<class 'numpy.float32'>)))))))

Verifying Networks:
N:
2021-06-30 17:16:59.885354: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
Input_0                         : Input([ 1  1 28 28], dtype=float32)
Reshape_0                       : Reshape(Input_0, [ -1 784])
Gemm_0                          : Gemm(Reshape_0, ndarray(shape=(784, 50)), ndarray(shape=(50,)))
Relu_0                          : Relu(Gemm_0)
Gemm_1                          : Gemm(Relu_0, ndarray(shape=(50, 50)), ndarray(shape=(50,)))
Relu_1                          : Relu(Gemm_1)
Gemm_2                          : Gemm(Relu_1, ndarray(shape=(10, 50)), ndarray(shape=(10,)))
Relu_2                          : Relu(Gemm_2)

dnnv.verifiers.neurify
  result: NeurifyTranslatorError(Unsupported computation graph detected)
  time: 0.7098

```

Thank you so much for your time.

**Comment by dlshriver** [comment]
Hi @GuantingPan,

Thank you for your interest in DNNV.

To answer your question, this specific error occurs because you are slicing the network to start at layer 3 with `export INPUT_LAYER=3`, which is the `Relu_0` operation, and Neurify does not support starting with just a Relu, it requires a fully connected layer (MatMul->Add->Relu or Gemm->Relu). We could probably try to identify these types of instances and stick a Gemm operation in there, but DNNV still won't work with this property and network.

That property was not written for MNIST networks, it is used in our test suite on some small handmade networks. It expects the input to be a flat tensor and has only 2 outputs (which isn't true of MNIST). You might be able to check this property by setting the environment variable `export INPUT_LAYER=2` so that it uses the first fully connected layer after the reshape, but this property is not really meaningful for this network. Also, this specific specification uses a random input point as the center of the input region every time, which is almost certainly not what you want in general. The properties in `tests/artifacts/properties` are really just used for the DNNV test suite and are not generally applicable to all networks.

If you want to check some actual MNIST examples, we have converted the ERAN-MNIST benchmark into the DNNP and ONNX formats [here](http://cs.virginia.edu/~dls2fc/eranmnist_benchmark.tar.gz).

**Comment by GuantingPan** [comment]
Thank you so much for your help!
